Repository Dhali-org/Dhali-app, pull requests merged in 2023-06, with the labels that each got.

#51 Add analytics
  lib/main.dart
  web/index.html
Labels: enhancement

#52 add warning bar
  lib/main.dart
  lib/marketplace/marketplace_home_screen.dart
Labels: enhancement

#53 Add Google Analytics
  lib/main.dart
  lib/marketplace/marketplace_home_screen.dart
  web/index.html
Labels: enhancement

#54 Ux tweaks
  lib/app_theme.dart
  lib/consumer_workflow.dart
  lib/marketplace/marketplace_dialogs.dart
  lib/marketplace/marketplace_home_screen.dart
  test/consumer_workflow_demo_test.dart
  web/index.html
Labels: enhancement

#56 fix deployment cost widget colours
  lib/marketplace/marketplace_dialogs.dart
Labels: enhancement

#55 UX tweaks
  lib/app_theme.dart
  lib/consumer_workflow.dart
  lib/marketplace/marketplace_dialogs.dart
  lib/marketplace/marketplace_home_screen.dart
  test/consumer_workflow_demo_test.dart
  web/index.html
Labels: enhancement

#57 disable analytics
  web/index.html
Labels: bug

#58 Disable analytics
  web/index.html
Labels: bug

#60 Re enable analytics
  web/index.html
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: bug, enhancement

#61 Re-enable analytics, support XUMM
  lib/consumer_workflow.dart
  lib/main.dart
  lib/marketplace/asset_page.dart
  lib/marketplace/marketplace_dialogs.dart
  lib/marketplace/marketplace_home_screen.dart
  lib/navigation_home_screen.dart
  lib/utils/Uploaders.dart
  lib/utils/payment.dart
  pubspec.yaml
  test/consumer_workflow_demo_test.dart
  test/consumer_workflow_demo_test.mocks.dart
  test/image_deployment_demo_test.dart
  test/image_deployment_demo_test.mocks.dart
  web/index.html
Labels: bug, enhancement

#62 use consent preferences in analytics
  web/index.html
Labels: bug

#63 Fix script blocking
  web/index.html
Labels: bug

#64 Some ux tweaks
  lib/marketplace/asset_page.dart
  lib/marketplace/filters_screen.dart
  lib/marketplace/marketplace_dialogs.dart
  lib/marketplace/marketplace_home_screen.dart
  lib/navigation_home_screen.dart
  lib/utils/show_popup_text_with_link.dart
  test/consumer_workflow_demo_test.dart
  test/image_deployment_demo_test.dart
Labels: bug, enhancement

#65 UX tweaks
  lib/marketplace/asset_page.dart
  lib/marketplace/filters_screen.dart
  lib/marketplace/marketplace_dialogs.dart
  lib/marketplace/marketplace_home_screen.dart
  lib/navigation_home_screen.dart
  lib/utils/show_popup_text_with_link.dart
  test/consumer_workflow_demo_test.dart
  test/image_deployment_demo_test.dart
Labels: bug, enhancement

#66 run 'dart fix'
  .github/workflows/lint.yaml
  lib/app_theme.dart
  lib/consumer_workflow.dart
  lib/help_screen.dart
  lib/main.dart
  lib/marketplace/asset_page.dart
  lib/marketplace/filters_screen.dart
  lib/marketplace/marketplace_app_theme.dart
  lib/marketplace/marketplace_dialogs.dart
  lib/marketplace/marketplace_home_screen.dart
  lib/marketplace/marketplace_list_view.dart
  lib/marketplace/range_slider_view.dart
  lib/marketplace/slider_view.dart
  lib/navigation_home_screen.dart
  lib/utils/Uploaders.dart
  lib/utils/not_implemented_dialog.dart
  lib/utils/show_popup_text_with_link.dart
  test/consumer_workflow_demo_test.dart
  test/image_deployment_demo_test.dart
  test/my_assets_test.dart
Labels: enhancement

#67 inject env gtags
  .github/workflows/firebase-hosting-merge-prod.yml
  .github/workflows/firebase-hosting-merge-staging.yml
  .github/workflows/firebase-hosting-pull-request.yml
  web/gtm_body_prod.html
  web/gtm_body_staging.html
  web/gtm_head_prod.html
  web/gtm_head_staging.html
  web/index.html
Labels: enhancement

#68 Env-based gtags
  .github/workflows/firebase-hosting-merge-prod.yml
  .github/workflows/firebase-hosting-merge-staging.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/lint.yaml
  lib/app_theme.dart
  lib/consumer_workflow.dart
  lib/help_screen.dart
  lib/main.dart
  lib/marketplace/asset_page.dart
  lib/marketplace/filters_screen.dart
  lib/marketplace/marketplace_app_theme.dart
  lib/marketplace/marketplace_dialogs.dart
  lib/marketplace/marketplace_home_screen.dart
  lib/marketplace/marketplace_list_view.dart
  lib/marketplace/range_slider_view.dart
  lib/marketplace/slider_view.dart
  lib/navigation_home_screen.dart
  lib/utils/Uploaders.dart
  lib/utils/not_implemented_dialog.dart
  lib/utils/show_popup_text_with_link.dart
  test/consumer_workflow_demo_test.dart
  test/image_deployment_demo_test.dart
  test/my_assets_test.dart
  web/gtm_body_prod.html
  web/gtm_body_staging.html
  web/gtm_head_prod.html
  web/gtm_head_staging.html
  web/index.html
Labels: enhancement

#69 fix broken script tag
  web/gtm_head_prod.html
Labels: bug

#71 fix broken script tag again(!)
  web/gtm_head_prod.html
Labels: bug

#70 Fix broken GA script tag
  web/gtm_head_prod.html
Labels: bug

#76 fix prod gtags body snippet
  web/gtm_body_prod.html
Labels: bug

#78 add missing gtags
  web/gtm_head_prod.html
  web/gtm_head_staging.html
Labels: bug

#79 fix ga
  web/gtm_head_prod.html
  web/gtm_head_staging.html
Labels: bug

#85 add prompts to activate wallet
  lib/analytics/analytics.dart
  lib/navigation_home_screen.dart
Labels: enhancement

#86 Add split view
  lib/main.dart
  lib/navigation_home_screen.dart
  pubspec.yaml
Labels: enhancement

#89 add prod optimize container
  web/index.html
Labels: bug, enhancement

#92 load Goolgle Optimize first
  web/index.html
Labels: bug

#94 exclude mobile from resolution check
  lib/utils/display_utils.dart
Labels: bug

#95 misc fixes
  lib/utils/display_utils.dart
  pubspec.yaml
Labels: bug
