Repository Dhali-org/Dhali-app, pull requests merged in 2023-07, with the labels that each got.

#97 Tweak not implemented widget
  lib/navigation_home_screen.dart
  lib/utils/not_implemented_dialog.dart
  web/index.html
Labels: enhancement

#98 Activate new features
  lib/navigation_home_screen.dart
  test/my_assets_test.dart
Labels: bug, enhancement

#102 add warmup route
  assets/public.json
  assets/public.staging.json
Labels: enhancement

#103 config updates
  assets/public.json
  assets/public.staging.json
  lib/marketplace/asset_page.dart
Labels: enhancement

#104 Dart format
  .github/workflows/lint.yaml
  lib/marketplace/marketplace_app_theme.dart
  lib/marketplace/marketplace_home_screen.dart
  lib/marketplace/marketplace_list_view.dart
  lib/utils/Uploaders.dart
Labels: enhancement

#107 add missing warmup route to prod
  assets/public.prod.json
Labels: bug

#108 Fix prod deployments
  .github/workflows/lint.yaml
  assets/public.json
  assets/public.prod.json
  assets/public.staging.json
  lib/marketplace/marketplace_app_theme.dart
  lib/marketplace/marketplace_home_screen.dart
  lib/marketplace/marketplace_list_view.dart
  lib/utils/Uploaders.dart
Labels: bug, enhancement

#110 gtag when asset displayed
  lib/marketplace/asset_page.dart
Labels: enhancement

#113 add gtag for linked wallet
  lib/navigation_home_screen.dart
Labels: enhancement

#114 More gtags
  assets/public.json
  assets/public.prod.json
  assets/public.staging.json
  lib/marketplace/asset_page.dart
  lib/navigation_home_screen.dart
Labels: enhancement

#111 Add warmup and correct inference calc
  lib/consumer_workflow.dart
  test/consumer_workflow_demo_test.dart
  test/image_deployment_demo_test.dart
  test/utils.dart
Labels: bug, enhancement

#116 add gtag on create asset click
  lib/marketplace/marketplace_home_screen.dart
Labels: enhancement

#117 More gtags
  lib/marketplace/marketplace_home_screen.dart
Labels: enhancement
