Repository Dhali-org/Dhali-app, pull requests merged in 2023-03, with the labels that each got.

#5 use 'xrpl.dart' package
  lib/wallet/home_screen.dart
  lib/wallet/xrpl_bindings.dart
  lib/wallet/xrpl_wallet.dart
  pubspec.yaml
Labels: enhancement

#6 Use .then async procedure to set balance
  lib/wallet/home_screen.dart
  lib/wallet/xrpl_wallet.dart
  test/image_deployment_demo_test.mocks.dart
Labels: bug, enhancement

#7 Merge into main
  lib/wallet/home_screen.dart
  lib/wallet/xrpl_bindings.dart
  lib/wallet/xrpl_wallet.dart
  pubspec.yaml
  test/image_deployment_demo_test.mocks.dart
Labels: bug, enhancement

#14 correct wallet display text
  lib/wallet/home_screen.dart
Labels: bug

#16 My asset filter
  lib/marketplace/marketplace_home_screen.dart
  lib/marketplace/marketplace_list_view.dart
  lib/utils/ChunkUploader.dart
  lib/wallet/xrpl_wallet.dart
  pubspec.yaml
  test/image_deployment_demo_test.dart
  test/my_assets_test.dart
  test/utils.dart
Labels: enhancement
